// Do not edit. This file is machine generated by the Resource DLL Wizard.
//---------------------------------------------------------------------------
#define PACKAGE __declspec(package)
#define USERC(FileName) extern PACKAGE _Dummy
#define USERES(FileName) extern PACKAGE _Dummy
#define USEFORMRES(FileName, FormName, AncestorName) extern PACKAGE _Dummy
#pragma hdrstop
int _turboFloat;
//---------------------------------------------------------------------------
/*ITE*/ /*DFMFileType*/ /*UCadastroFuncionario.dfm*/
/*ITE*/ /*DFMFileType*/ /*UCadastroNatural.dfm*/
/*ITE*/ /*DFMFileType*/ /*UCadClienteContribuintePF.dfm*/
/*ITE*/ /*DFMFileType*/ /*UCadClienteContribuintePJ.dfm*/
/*ITE*/ /*DFMFileType*/ /*UConsAtuaExcSocio.dfm*/
/*ITE*/ /*DFMFileType*/ /*UDoacao.dfm*/
/*ITE*/ /*DFMFileType*/ /*UInicio.dfm*/
/*ITE*/ /*DFMFileType*/ /*UMatricula.dfm*/
/*ITE*/ /*DFMFileType*/ /*UResumo.dfm*/
/*ITE*/ /*DFMFileType*/ /*UTipoConsultaSocio.dfm*/
/*ITE*/ /*DFMFileType*/ /*UTpConsultaDoacao.dfm*/
/*ITE*/ /*DFMFileType*/ /*UTpConsultaResumo.dfm*/
/*ITE*/ /*RCFileType*/ /*Associacao_DRC.rc*/
//---------------------------------------------------------------------------
USEFORMRES("UCadastroFuncionario.dfm", Form3, Form); /* TForm: DesignClass */
USEFORMRES("UCadastroNatural.dfm", Form4, Form); /* TForm: DesignClass */
USEFORMRES("UCadClienteContribuintePF.dfm", Form2, Form); /* TForm: DesignClass */
USEFORMRES("UCadClienteContribuintePJ.dfm", Form5, Form); /* TForm: DesignClass */
USEFORMRES("UConsAtuaExcSocio.dfm", Form6, Form); /* TForm: DesignClass */
USEFORMRES("UDoacao.dfm", Form10, Form); /* TForm: DesignClass */
USEFORMRES("UInicio.dfm", Form1, Form); /* TForm: DesignClass */
USEFORMRES("UMatricula.dfm", Form12, Form); /* TForm: DesignClass */
USEFORMRES("UResumo.dfm", Form8, Form); /* TForm: DesignClass */
USEFORMRES("UTipoConsultaSocio.dfm", Form7, Form); /* TForm: DesignClass */
USEFORMRES("UTpConsultaDoacao.dfm", Form11, Form); /* TForm: DesignClass */
USEFORMRES("UTpConsultaResumo.dfm", Form9, Form); /* TForm: DesignClass */
USERC("Associacao_DRC.rc");
//---------------------------------------------------------------------------
#define DllEntryPoint
